version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: mongos
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand({ ping: 1 }).ok"]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped

  web:
    build: .
    container_name: web3
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongo:27017/
      - MONGO_DB=netops
      - MONGO_COLL=routers
    depends_on:
      mongo:
        condition: service_healthy
    restart: unless-stopped

volumes:
  mongo-data:
